### ISSUE TITLE
Add meta data for new ray tracing buffer usages

### ISSUE THREAD

**Issue by johannesugb** [cg-tuwien/Auto-Vk#41]
With the official `VK_KHR_ray_tracing` extension, additional buffer usage flags have been introduced (and `vk::BufferUsageFlagBits::eRayTracingKHR` has been removed).

Add new meta data for the new buffer usages:
- [ ] Shader Binding Table (see `avk.cpp#L6309`)
- [ ] Acceleration Structure (see `avk.hpp#L256`)
- [ ] Anything else? Did I forget anything?

**Comment by johannesugb** [comment]
The framework offers the following additional meta types:
- `aabb_buffer_meta`
- `geometry_instance_buffer_meta`
- `read_only_input_to_acceleration_structure_builds_buffer_meta`
